name: CI Pipeline

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Remove old images
        run: |
          docker rmi chumaedeogu/test:${{ steps.vars.outputs.short_sha }} || true
          docker rmi chumaedeogu/test:latest || true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            chumaedeogu/test:${{ steps.vars.outputs.short_sha }}
            chumaedeogu/test:latest
